#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CarouselView.Resource", IsApplication=false)]

namespace CarouselView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public static int animateOnBoundary = 2130771985;
			
			// aapt resource value: 0x7f01000d
			public static int autoPlay = 2130771981;
			
			// aapt resource value: 0x7f010004
			public static int centered = 2130771972;
			
			// aapt resource value: 0x7f01000e
			public static int disableAutoPlayOnUserInteraction = 2130771982;
			
			// aapt resource value: 0x7f010008
			public static int fillColor = 2130771976;
			
			// aapt resource value: 0x7f010001
			public static int indicatorGravity = 2130771969;
			
			// aapt resource value: 0x7f01000f
			public static int indicatorMarginHorizontal = 2130771983;
			
			// aapt resource value: 0x7f010010
			public static int indicatorMarginVertical = 2130771984;
			
			// aapt resource value: 0x7f010002
			public static int indicatorOrientation = 2130771970;
			
			// aapt resource value: 0x7f010009
			public static int pageColor = 2130771977;
			
			// aapt resource value: 0x7f010007
			public static int pageTransformInterval = 2130771975;
			
			// aapt resource value: 0x7f010003
			public static int pageTransformer = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public static int radius = 2130771978;
			
			// aapt resource value: 0x7f010006
			public static int slideInterval = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public static int snap = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int strokeColor = 2130771980;
			
			// aapt resource value: 0x7f010005
			public static int strokeWidth = 2130771973;
			
			// aapt resource value: 0x7f010000
			public static int vpiCirclePageIndicatorStyle = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f040000
			public static int default_circle_indicator_centered = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int default_circle_indicator_snap = 2130968577;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030008
			public static int default_circle_indicator_fill_color = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int default_circle_indicator_page_color = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int default_circle_indicator_stroke_color = 2130903050;
			
			// aapt resource value: 0x7f030000
			public static int vpi__background_holo_dark = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int vpi__background_holo_light = 2130903041;
			
			// aapt resource value: 0x7f030004
			public static int vpi__bright_foreground_disabled_holo_dark = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int vpi__bright_foreground_disabled_holo_light = 2130903045;
			
			// aapt resource value: 0x7f030002
			public static int vpi__bright_foreground_holo_dark = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int vpi__bright_foreground_holo_light = 2130903043;
			
			// aapt resource value: 0x7f030006
			public static int vpi__bright_foreground_inverse_holo_dark = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int vpi__bright_foreground_inverse_holo_light = 2130903047;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int default_circle_indicator_radius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int default_circle_indicator_stroke_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int default_indicator_margin_horizontal = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int default_indicator_margin_vertical = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public static int bottom = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int center = 2131230721;
			
			// aapt resource value: 0x7f080002
			public static int center_horizontal = 2131230722;
			
			// aapt resource value: 0x7f080003
			public static int center_vertical = 2131230723;
			
			// aapt resource value: 0x7f08000f
			public static int containerViewPager = 2131230735;
			
			// aapt resource value: 0x7f08000b
			public static int depth = 2131230731;
			
			// aapt resource value: 0x7f080004
			public static int end = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public static int flow = 2131230732;
			
			// aapt resource value: 0x7f080009
			public static int horizontal = 2131230729;
			
			// aapt resource value: 0x7f080010
			public static int indicator = 2131230736;
			
			// aapt resource value: 0x7f080005
			public static int left = 2131230725;
			
			// aapt resource value: 0x7f080006
			public static int right = 2131230726;
			
			// aapt resource value: 0x7f08000d
			public static int slide_over = 2131230733;
			
			// aapt resource value: 0x7f080007
			public static int start = 2131230727;
			
			// aapt resource value: 0x7f080008
			public static int top = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public static int vertical = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public static int zoom = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public static int default_circle_indicator_orientation = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int view_carousel = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public static int app_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CarouselView = new int[]
			{
					2130771969,
					2130771970,
					2130771971,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 15
			public static int CarouselView_animateOnBoundary = 15;
			
			// aapt resource value: 11
			public static int CarouselView_autoPlay = 11;
			
			// aapt resource value: 12
			public static int CarouselView_disableAutoPlayOnUserInteraction = 12;
			
			// aapt resource value: 6
			public static int CarouselView_fillColor = 6;
			
			// aapt resource value: 0
			public static int CarouselView_indicatorGravity = 0;
			
			// aapt resource value: 13
			public static int CarouselView_indicatorMarginHorizontal = 13;
			
			// aapt resource value: 14
			public static int CarouselView_indicatorMarginVertical = 14;
			
			// aapt resource value: 1
			public static int CarouselView_indicatorOrientation = 1;
			
			// aapt resource value: 7
			public static int CarouselView_pageColor = 7;
			
			// aapt resource value: 5
			public static int CarouselView_pageTransformInterval = 5;
			
			// aapt resource value: 2
			public static int CarouselView_pageTransformer = 2;
			
			// aapt resource value: 8
			public static int CarouselView_radius = 8;
			
			// aapt resource value: 4
			public static int CarouselView_slideInterval = 4;
			
			// aapt resource value: 9
			public static int CarouselView_snap = 9;
			
			// aapt resource value: 10
			public static int CarouselView_strokeColor = 10;
			
			// aapt resource value: 3
			public static int CarouselView_strokeWidth = 3;
			
			public static int[] CirclePageIndicator = new int[]
			{
					16842948,
					16842964,
					2130771972,
					2130771973,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public static int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public static int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public static int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public static int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public static int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public static int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public static int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public static int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public static int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public static int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
